"not strict";

require("./distraer.scss");

var _distraerA = require("./distraerA");

var _distraerC = require("./distraerC");

window.onload = function () {
  let x = document.createElement("div");
  x.setAttribute("id", "progreso");
  x.setAttribute("class", "contenedor");
  document.body.appendChild(x);
  let pr = document.createElement("PROGRESS");
  pr.setAttribute("id", "ProgresoB");
  pr.setAttribute("value", 50);
  pr.setAttribute("max", 100);
  document.getElementById("progreso").appendChild(pr);
  let h1 = document.createElement("h1");
  h1.setAttribute = ("id", "Titulo");
  let textNode = document.createTextNode("Decides distraerlo");
  h1.appendChild(textNode);
  document.body.appendChild(h1);
  let h3 = document.createElement("h3");
  h3.setAttribute = ("id", "Texto1");
  textNode = document.createTextNode("Decides distraer al monstruo");
  h3.appendChild(textNode);
  textNode = document.createElement("br");
  h3.appendChild(textNode);
  textNode = document.createTextNode("Agarras esa roca y la tiras hacia la dirección del minotauro..");
  h3.appendChild(textNode);
  textNode = document.createElement("br");
  h3.appendChild(textNode);
  textNode = document.createTextNode("'Hm...?' El minotauro se mueve en aquella dirección, dejantote a ti y a Ana solos.");
  h3.appendChild(textNode);
  textNode = document.createElement("br");
  h3.appendChild(textNode);
  textNode = document.createTextNode('"Gracias que ya se fue." Dice Ana. "Hey! Mira lo que esta en el piso!"');
  h3.appendChild(textNode);
  textNode = document.createElement("br");
  h3.appendChild(textNode);
  textNode = document.createTextNode("En el suelo, encuentras una ");
  h3.appendChild(textNode);
  let b = document.createElement("b");
  let i = document.createElement("i");
  textNode = document.createTextNode('llave');
  i.appendChild(textNode);
  b.appendChild(i);
  h3.appendChild(b);
  textNode = document.createTextNode(', más grande a comparación de la que esta en la celda.');
  h3.appendChild(textNode);
  textNode = document.createElement("br");
  h3.appendChild(textNode);
  textNode = document.createTextNode('"Tal vez nos ayude! Vamos"');
  h3.appendChild(textNode);
  document.body.appendChild(h3);
  let detalles = document.createElement("details");
  detalles.setAttribute = ("id", "details");
  let summary = document.createElement("summary");
  summary.setAttribute = ("id", "summary");
  summary.innerHTML = "En que dirección te dirijes?";
  let ul = document.createElement("ol");
  ul.setAttribute = ("id", "decisiones");
  let li = document.createElement("li");
  li.setAttribute = ("id", "opcion1");
  li.innerHTML = "<div><button id = left type=button>Izquierda</button>";
  ul.appendChild(li);
  li = document.createElement("li");
  li.setAttribute = ("id", "opcion2");
  li.innerHTML = "<div><button id = right type=button>Derecha</button>";
  ul.appendChild(li);
  detalles.appendChild(summary);
  detalles.appendChild(ul);
  document.body.appendChild(detalles);
  (0, _distraerA.derecha)();
  (0, _distraerC.izquierda)();
};